config/routes.rb
Rails.application.routes.draw do
  get 'jobs/index'

  get 'jobs/new'

  get 'jobs/create'

  get 'jobs/show'

  devise_for :users
  root 'homes#index'
  resources :jobs, only: [:index, :new, :create, :show] do
  	resources :entries
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :entries, dependent: :destroy #この一行を追加
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :jobs, dependent: :destroy
  has_many :entries, dependent: :destroy #この一行を追加

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :store_user_location!, if: :storable_location?

 def storable_location?
   request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
 end

 def store_user_location!
   # :user is the scope we are authenticating
   store_location_for(:user, request.fullpath)
 end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def create
  	@entry = current_user.entries.new(entry_params)
  	if @entry.save
        flash[:notice] = "チャレンジを送りましました"
        redirect_to @entry.job, notice: "チャレンジが認められました。"
    else
        flash[:alert] = "チャレンジが認められませんでした"
        redirect_to :back
    end
  end

  private

  def entry_params
  	params.require(:entry).permit(:user_id, :job_id, :messages)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, except: :show
  def index
    @jobs = Job.all.includes(:user).where(user_id: current_user.id) #user_idがcurrent_user.idのJobを取得
    @entries = Entry.all.includes(:user,:job) #Entryを取得
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    image = Magick::ImageList.new('./public/twitter_ogp.png')
      draw = Magick::Draw.new
      title = cut_text(@job.title)
      draw.annotate(image, 0, 0, 0, -120, title) do
        self.font = 'app/assets/NotoSansJP-Bold.otf' #日本語対応可能なフォントにする
        self.fill = '#fff' #フォントの塗りつぶし色
        self.gravity = Magick::CenterGravity #描画基準位置(中央)
        self.font_weight = Magick::BoldWeight #フォントの太さ
        self.stroke = 'transparent' #フォント縁取り色(透過)
        self.pointsize = 48 #フォントサイズ（48pt）
      end
    image_path = image.write(uniq_file_name).filename #書き出したファイルのファイル名前
    image_url = cut_path(image_path) #不要なパスをcutする
    @job.image_url = image_url #@jobのimage_urlにcutしたimage_urlを代入
    if @job.save
        flash[:notice] = "チャレンジが保存されました"
        redirect_to @job
    else
        flash[:alert] = "チャレンジに失敗しました"
    end
  end

  def show
    @job = Job.find(params[:id])
    @entries = Entry.where(job_id:@job) #この一行を追加
  end

  private

  def cut_path(url)
    url.sub(/\.\/public\//, "")
  end

  def uniq_file_name
    "./public/#{SecureRandom.hex}.png"
  end

  def cut_text(text)
      text.scan(/.{1,15}/).join("\n")
  end

  def job_params
	params.require(:job).permit(:title, :content).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/entries/create.html.erb
<h1>Entries#create</h1>
<p>Find me in app/views/entries/create.html.erb</p>

app/views/homes/index.html.erb
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <h1 class="intro-lead-in h1">SNSを使って<br>1on1を募集しよう！</h1>
      <div class="intro-heading">1on1はSNSで1on1する相手を募集をすることができるサービスです。</div>
      <div class="intro-button">
        <!-- ==========ここから追加する========== -->
        <%= link_to '今すぐ始める', new_job_path , class: "btn btn-xl" %>
        <!-- ==========ここまで追加する========== -->
      </div>
    </div>
  </div>
</header>
<section class="features-icons  bg-2 text-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
          <div class="features-icons-icon">
            <i class="far fa-comment" style="font-size:80px;"></i>
          </div>
          <h3>SNSでカンタン募集</h3>
          <p class="lead mb-0">SNS上にあなたの募集情報を投稿して<br>もっと手軽にバスケできる人を集めましょう。</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
          <div class="features-icons-icon">
            <i class="far fa-image" style="font-size:80px;"></i>
          </div>
          <h3>シェア画像も自動生成</h3>
          <p class="lead mb-0">募集タイトルと詳細を入力するだけで<br>SNS用の画像を作ってくれます。</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-0 mb-lg-3">
          <div class="features-icons-icon">
            <i class="far fa-envelope" style="font-size:80px;"></i>
          </div>
          <h3>無駄なやり取りなし</h3>
          <p class="lead mb-0">気に入った人にだけ返事をするので、<br>無駄なやり取りは発生しません。</p>
        </div>
      </div>
    </div>
  </div>
</section>
<footer class="footer bg-2">
  <div class="container text-center">
    <span class="text-muted">© oneonone</span>
</footer>

app/views/jobs/create.html.erb
<h1>Jobs#create</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/jobs/index.html.erb
<header class="masthead">
	<div class="container">
		<div class="intro-text">
			<h2 class="intro-lead-in h2">1on1を募集しよう！</h2>
			<div class="intro-button">
				<%= link_to '今すぐ始める', new_job_path , class: "btn btn-xl" %>
			</div>
		</div>
	</div>
</header>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-1">
			<div class="job-show-left">
				<h2 class="job-list-title"><%= current_user.email %>さんの募集一覧</h2>
				<ul class="list-group">
					<% @jobs.each do |job| %><!-- ①： 仕事一覧の表示 -->
						<%= link_to job_path(job), class: "no-text-decoration" do %>
							<li class="list-group">
								<div class="card">
									<img class="card-img-bottom" src="/<%= job.image_url %>" alt="">
									<div class="card-body">
										<h5 class="card-title"><%= job.title %></h5>
										<p class="card-text"><%= job.content %></p>
										<p class="card-text"><small class="text-muted"><%= job.created_at.strftime('%Y/%m/%d %H:%M') %></small></p>
									</div>
								</div>
							</li>
						<% end %>
					<% end %>
				</ul>
			</div>
		</div>
		<div class="col-md-4 ">
			<div class="job-show-left">
				<h2 class="entry-list-title">新着応募</h2>
				<ul class="list-group">
						<% @entries.each do |entry| %>
								<% if entry.job.user_id == current_user.id %><!-- ②：自分の作成した募集へのエントリーの場合 -->
									<li class="list-group-item">
										<div><%= entry.job.user.email %>　<small class="text-muted"><%= entry.job.created_at.strftime('%Y/%m/%d %H:%M') %></small></div>
										<div class="list-group-item-comment">
											<%= entry.messages %>
										</div>
									</li>
								<% end %>
						<% end %>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/jobs/new.html.erb
<div class="container jobs-new">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= form_with model: @job do |f| %>
        <div class="form-group">
          <label for="exampleInputTitle">募集タイトル</label>
          <%= f.text_field :title , class: "form-control", placeholder: "募集タイトルを入力してください" %>
        </div>
        <div class="form-group">
          <label for="exampleInputDetail">募集内容詳細</label>
          <%= f.text_area :content , class: "form-control", placeholder: "例：Techpitを手伝ってくれる人を募集します！" %>
        </div>
        <div class="intro-button text-center">
           <%= f.submit "募集を作る", class: "btn btn-xl" %>
              </div>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<% content_for :ogp do %>
  <meta property="og:title" content="<%= @job.title %>" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="/jobs/<%= @job.id %>" />
  <meta property="og:image" content=<%= "#{root_url}#{@job.image_url}" %> />
  <meta property="og:site_name"  content="Techpit_Job" />
  <meta property="og:description" content="<%= @job.content %>" />
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@techpit_jp" />
<% end %>
<!-- ここまでを追加する -->

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="job-show">
        <ul class="list-group">
          <li class="list-group">
            <div class="card">
              <img class="card-img-bottom" src="/<%= @job.image_url %>" alt="Card image cap"><!-- ① -->
              <div class="card-body">
                <h5 class="card-title"><%= @job.title %></h5>
                <p class="card-text"><%= @job.content %></p>
                <!-- ② -->
                <p class="card-text"><small class="text-muted"><%= @job.created_at.strftime('%Y/%m/%d %H:%M')  %></small></p>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="job-show-share">
        <div class="social text-center">
          <a href="https://twitter.com/intent/tweet?url=http://techpit.jp&text=テックピット&hashtags=#techpit" rel="nofollow" class="btn btn-xl btn-tw" target="_blank">twiterに投稿</a>
        </div>
        <p class="share-url"><a onclick="clipURL()" class="url-text">URL</a><i class="far fa-copy"></i></p>
      </div>
      <% if user_signed_in? %> <!-- ③：ログインしている場合 -->
        <% if @job.user_id == current_user.id %> <!-- ④：自分の作成した求人だった場合 -->
          <div class="job-show-comment">
            <h2 class="job-list-title">応募一覧</h2>
            <ul class="list-group">
              <% @entries.each do |entry| %>
                <li class="list-group-item">
                    <div><%= entry.user.email %>　<small class="text-muted"><%= entry.created_at.strftime('%Y/%m/%d %H:%M') %></small></div>
                    <div class="list-group-item-comment">
                      <%= entry.messages %>
                    </div>
                  </li>
              <% end %>
            </ul>
          </div>
        <% else -%> <!-- ④：自分の作成した求人でない場合 -->
        <% if current_user.entries.where(job_id: @job.id).present? %><!-- ⑤すでに応募している場合 -->
          <div class="intro-button text-center">
          <a href="javascript:void(0)" class="btn btn-xl">すでに応募しています</a>
        </div>
        <% else %><!-- ⑤まだ応募していない場合 -->
         <%= form_with model: [@job, @job.entries.new] do |f| %>
            <%= f.hidden_field :job_id, value: @job.id %>
            <div class="form-group form-message">
              <label for="exampleInputMessage">メッセージ（任意）</label>
              <%= f.text_area :messages , class: "form-control", placeholder: "例：興味あります。よければDMでご連絡お待ちしております。" %>
            </div>
            <div class="intro-button text-center">
               <%= f.submit "応募する", class: "btn btn-xl" %>
                  </div>
          <% end %>
        <% end %><!-- ⑤ -->
      <% end %><!-- ④ -->

    <% else %><!-- ③：ログインしていない場合 -->
      <div class="show-login text-center">
        <div class="intro-button text-center">
          <a href="/users/sign_in" class="btn btn-xl">応募する</a>
        </div>
        <p>応募するには会員登録・ログインの必要がございます</p>
      </div>
      <div class="job-show-comment">
        <h2 class="job-list-title">ご応募後の流れ</h2>
        <p>1. 応募するとアカウント情報が相手に届きます。</p>
        <p>2. 必ず連絡が来るわけではありません。</p>
        <p>3. 募集者がマッチしたと思った場合メッセージを送ります。</p>
        <p>4. メッセージは連携SNSで届きます。</p>
        <p>※ Twitterで応募した場合は「」で「すべてのユーザーからダイレクトメッセージを受信する」 にチェックを入れてください。</p>
        </ul>
      </div>
      <% end %><!-- ③ -->

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechpitJobs</title>
    <%= csrf_meta_tags %>
  	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><!-- この一行を追加:viewportの設定 -->
    <%= yield :ogp %><!-- この一行を追加 -->
    <meta http-equiv="content-type" content="text/html; charset=utf-8" /><!-- 文字コードの指定-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous"><!-- この一行を追加:font-awsomeの設定 -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <!-- ここから追加 -->
  <nav class="navbar navbar-expand-lg bg-2 navbar-light header">
    <div class="container">
      <a class="navbar-brand" href="/jobs">1on1</a>
      <% if user_signed_in? %>
      <div class="my-2 my-lg-0">
          <%= link_to 'ログアウト', destroy_user_session_path, class: "no-text-decoration", method: :delete %><!-- link_toメソッドを使ってログアウト用のリンクを用意 -->
        </div>
      <% end %>
    </div>
  </nav>
  <!-- ここまで -->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  <script>
    $('.url-text').text(document.URL); //url-textクラスを現在のURL（document.URL）に変更する
    function clipURL() { //clipURL関数の定義（urlをコピーする機能）
      $('body').append('<textarea id="currentURL" style="position:fixed;left:-100%;">'+location.href+'</textarea>');//コピー用のtextareaを作成
      $('#currentURL').select(); //currentURLのIDを選択
      document.execCommand('copy'); //選択しているテキストをクリップボードにコピーする
      $('#currentURL').remove(); //現在のcurrentURLのIDを削除
      alert("URLをコピーしました。");//アラートを表示する
    }
    var text = $('.card-title').text(); //textにcard-titleクラスのテキストを代入する
    var twitterurl = "https://twitter.com/intent/tweet?url=" + document.URL + "&text=" + text + "&hashtags=#テックピット";//twitterurlのシェア用urlを作成してtwitterurlに挿入
    $('.btn-tw').attr('href',twitterurl);//btn-twクラスのリンクをtwitterurlに変更する
  </script>
</body>
</html>